name: "Docker Release"
description: "Build and push docker container to registry"
inputs:
  aws-access-key-id:
    description: ""
    required: true
  aws-secret-access-key:
    description: ""
    required: true
  aws-region:
    description: ""
    required: true
  dockerfile:
    description: "The path to the dockerfile"
    default: "Dockerfile"
    required: false
  image-name:
    description: "The name for the image"
    required: true
  image-tag:
    description: "The image tag to use"
    required: true
  fury-token:
    description: "The token needed for gemfury"
    required: true
  target:
    description: ""
    default: "prod"
    required: false
  dockerfile-context:
    description: ""
    default: "."
    required: false

runs:
  using: "composite"
  steps:
    - name: Run Hadolint
      shell: bash
      run: |
        cd ${{ inputs.dockerfile-contex }}
        docker run --rm -i hadolint/hadolint < ${{ inputs.dockerfile }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1
      id: login_ecr

    - name: Build
      shell: bash
      run: |
        docker build --target ${{ inputs.target }} --build-arg FURY_AUTH_PULL=${{ inputs.fury-token }} ${{ inputs.dockerfile-contex }}

    - name: Push image to Amazon ECR
      shell: bash
      run: |
        set +e
        describe_image="$(aws ecr describe-images --repository-name ${{ inputs.image-name }} --image-ids imageTag=${{ inputs.image-tag }} 2> /dev/null)"
        if [ $? -eq 0 ]; then
          echo "Image ${{ inputs.image-tag }} already exists and will not be pushed again."
        else
          export name="${{ steps.login_ecr.outputs.registry }}/${{ inputs.image-name }}:${{ inputs.image-tag }}"
          docker build --file ${{ inputs.dockerfile }} --target ${{ inputs.target }} --build-arg FURY_AUTH_PULL=${{ inputs.fury-token }} -t $name ${{ inputs.dockerfile-context }}
          docker push $name
        fi
